apiVersion: v1
data:
  application.yaml: |
    spring:
      redis:
        host: redis-master
        port: 6379
        password: ${REDIS_PASSWORD}
kind: ConfigMap
metadata:
  labels:
    app: redis-demo
    appGroup: myhelsana
  name: redis-demo
  namespace: myhelsana
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-demo
    appGroup: myhelsana
    scrape: prometheus-spring-boot
  name: redis-service
  namespace: myhelsana
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: redis-demo
    appGroup: myhelsana
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-demo
    appGroup: myhelsana
  name: redis-service
  namespace: myhelsana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-demo
      appGroup: myhelsana
  template:
    metadata:
      labels:
        app: redis-demo
        appGroup: myhelsana
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: aks
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              key: user
              name: spring-encrypt
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: key
              name: spring-encrypt
        - name: JAVA_TOOL_OPTIONS
          value: '-Djavax.net.ssl.trustStore=/mnt/truststore/myhelsana-truststore.jks
            -Djavax.net.ssl.trustStoreType=JKS -Xms768m -Xmx768m -XX:MaxMetaspaceSize=256M
            -Duser.timezone=''Europe/Zurich'' '
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongodb-root-password
              name: mongodb
        - name: ENCRYPT_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: spring-encrypt
        image: myhelsana.azurecr.io/redis-demo:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 3
          timeoutSeconds: 5
        name: redis-demo
        ports:
        - containerPort: 8080
          name: 8080-tcp
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - mountPath: /mnt/truststore
          name: myhelsana-truststore
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: myhelsana-truststore
        secret:
          defaultMode: 420
          items:
          - key: truststore.jks
            path: myhelsana-truststore.jks
          secretName: myhelsana-truststore
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: redis-demo
    appGroup: myhelsana
    prometheus: apps
  name: redis-service
  namespace: myhelsana
spec:
  groups:
  - name: redis-demo-myhelsana
    rules:
    - alert: redis-demo-myhelsana-job_down
      annotations:
        message: '{{ $labels.job }}: state down'
        severity: critical
      expr: up{job="redis-demo", namespace="myhelsana"}== 0
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app: redis-demo
    appGroup: myhelsana
  name: redis-service-ingress
  namespace: myhelsana
spec:
  routes:
  - kind: Rule
    match: PathPrefix(`/redis`)
    middlewares:
    - name: test-stripprefix
    services:
    - name: redis-service
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app: redis-demo
    appGroup: myhelsana
  name: test-stripprefix
  namespace: myhelsana
spec:
  stripPrefix:
    prefixes:
    - /redis
