apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: redis
  appGroup: infra
  scrape: prometheus

commonAnnotations:
  splunk.com/index: myhelsana

images:
  - name: docker-registry.default.svc:5000/openshift/redis
    newTag: latest

resources:
  - deployment.yaml
  - svc.yaml
  - pvc.yaml

patchesStrategicMerge:
  - use-configmap.yaml
  - use-secret.yaml
  - patch-memorylimit.yaml
  - patch-healthcheck.yaml
