apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: c3smonkey/template
    newName: myhelsana.azurecr.io/redis-demo
    newTag: latest

namespace: myhelsana

commonLabels:
  app: redis-demo
  appGroup: myhelsana

resources:
  - ../base
  - ingress.yaml

# Patch Deployment
patchesStrategicMerge:
  - patch-spring-profile.yaml

# ConfigMap
configMapGenerator:
  - files:
      - config-files/application.yaml
    name: redis-demo
    options:
      disableNameSuffixHash: true
