apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: redis-demo
  scrape: prometheus
  appGroup: demo

resources:
  - deployment.yaml
  - roles.yaml

# ConfigMap
patchesStrategicMerge:
  - patch-spring-profile.yaml
  - use_configmap.yaml
  - use-redis-secret.yaml

configMapGenerator:
  - files:
      - config-files/application.yaml
    name: redis-demo

