apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: redis-

commonLabels:
  app: redis-demo
  appGroup: myhelsana

# Resources
resources:
  - deployment.yaml
  - service.yaml
  - prometheus

# ConfigMap
patchesStrategicMerge:
  - use-mongodb-secret.yaml
  - use-java-tool-options.yaml
  - use-actuator-secret.yaml
  - use-redis-secret.yaml

# otherwise the name wil be namePrefix-app-nameSuffix
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: service
    target:
      kind: Deployment
      name: .*
  - patch: |-
      - op: replace
        path: /metadata/name
        value: service
    target:
      kind: Service
      name: .*
  - target:
      kind: PrometheusRule
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: service
  - target:
      kind: Route
      name: .*
    patch: |-
      - op: replace
        path: /metadata/name
        value: service

